### ISSUE TITLE
Needs an option to retry building without re-downloading

### ISSUE THREAD

**Issue by RaghavRao** [pineappleEA/Pineapple-Linux#24]
I am on fedora and certain dependencies were missing (the instructions conflict with pipejack so I had to install with `--skip-broken` ) and I had to redownload the tar each time I ran the script.

Please add an option to re-try cmake if the tar was successfully downloaded and unzipped in the temp dir

**Comment by MGThePro** [comment]
It should automatically skip redownloading if the file exists since 37b23d9, please try it out and report back, as these things always seem to break when they're not running on my pc.

Also as a side note, if you're using aria2 it'll report an error, just ignore that and it'll continue a couple seconds later, I dont think there's a way around that with aria2's options.
